export * from './MakefileTemplate';
export * from './GitIgnoreTemplate';
export * from './ReadmeTemplate';
export * from './LicenseTemplate';
export * from './PackageExcludesTemplate';
export * from './CodeOfConductTemplate';
export * from './ContributingTemplate';
export * from './NvmRcTemplate';
export * from './TerraformToVarsTemplate';