import {AbstractPackage} from '@ohoareau/microgen';
import {GitIgnoreTemplate, LicenseTemplate, MakefileTemplate, ReadmeTemplate} from "@ohoareau/microgen-templates-core";
import RootReadmeTemplate from "./RootReadmeTemplate";
import {buildProjectsVars} from "./utils";

export default class Package extends AbstractPackage {
    protected getTemplateRoot(): string {
        return `${__dirname}/../templates`;
    }
    // noinspection JSUnusedLocalSymbols,JSUnusedGlobalSymbols
    protected buildDefaultVars(vars: any): any {
        return {
            project_prefix: 'mycompany',
            project_name: 'myproject',
            projects: [],
            scm: 'git',
        };
    }
    // noinspection JSUnusedLocalSymbols,JSUnusedGlobalSymbols
    protected buildDynamicFiles(vars: any, cfg: any): any {
        const files = {
            ['LICENSE.md']: this.buildLicense(vars),
            ['.gitignore']: this.buildGitIgnore(vars),
            ['Makefile']: this.buildMakefile(vars),
        };
        vars.readme && (files['README.md'] = this.buildReadme(vars));
        return files;
    }
    protected buildLicense(vars: any): LicenseTemplate {
        return new LicenseTemplate(vars);
    }
    protected buildReadme(vars: any): ReadmeTemplate {
        return new RootReadmeTemplate(vars)
        ;
    }
    protected buildGitIgnore(vars: any): GitIgnoreTemplate {
        return new GitIgnoreTemplate(vars.gitignore || {})
            .addGroup('Logs', [
                'logs', '*.log', 'npm-debug.log*', 'yarn-debug.log*', 'yarn-error.log*',
            ])
            .addGroup('Runtime data', [
                'pids', '*.pid', '*.seed', '*.pid.lock',
            ])
            .addGroup('Directory for instrumented libs generated by jscoverage/JSCover', [
                'lib-cov',
            ])
            .addGroup('Coverage directory used by tools like istanbul', [
                'coverage',
            ])
            .addGroup('nyc test coverage', [
                '.nyc_output',
            ])
            .addGroup('Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)', [
                '.grunt',
            ])
            .addGroup('Bower dependency directory (https://bower.io/)', [
                'bower_components',
            ])
            .addGroup('node-waf configuration', [
                '.lock-wscript',
            ])
            .addGroup('Compiled binary addons (http://nodejs.org/api/addons.html)', [
                'build/Release',
            ])
            .addGroup('Dependency directories', [
                'node_modules/', 'jspm_packages/',
            ])
            .addGroup('Typescript v1 declaration files', [
                'typings/',
            ])
            .addGroup('Optional npm cache directory', [
                '.npm',
            ])
            .addGroup('Optional eslint cache', [
                '.eslintcache',
            ])
            .addGroup('Optional REPL history', [
                '.node_repl_history',
            ])
            .addGroup("Output of 'npm pack'", [
                '*.tgz',
            ])
            .addGroup('dotenv environment variable files', [
                '.env*',
            ])
            .addGroup('Mac files', [
                '.DS_Store',
            ])
            .addGroup('Yarn', [
                'yarn-error.log', '.pnp/', '.pnp.js',
            ])
            .addGroup('Yarn Integrity file', [
                '.yarn-integrity',
            ])
            .addGroup('IDE files', [
                '.idea/'
            ])
            .addGroup('Terraform', [
                '.terraform/', '*.tfplan', '/outputs/', '*.zip'
            ])
        ;
    }
    protected buildMakefile(vars: any): MakefileTemplate {
        const scm = vars.scm || 'git';
        const {
            deployableProjects,
            buildablePostProjects,
            buildablePreProjects,
            buildableProjects,
            generateEnvLocalableProjects,
            installableProjects,
            preInstallableProjects,
            refreshableProjects,
            startableProjects,
            testableProjects,
        } = buildProjectsVars(vars);
        const t = new MakefileTemplate(vars.makefile || {})
            .addGlobalVar('env', 'dev')
            .addGlobalVar('b', vars.default_branch ? vars.default_branch : 'develop')
            .addPredefinedTarget('generate', 'yarn-microgen')
            .addPredefinedTarget('install-root', 'yarn-install')
            .addPredefinedTarget('install-terraform', 'tfenv-install')
            .addMetaTarget('pre-install-root', ['install-root'])
            .addMetaTarget('deploy', deployableProjects.map(p => `deploy-${p.name}`))
            .addMetaTarget('build', ['build-pre-provision', 'build-post-provision'])
            .addMetaTarget('build-pre-plan', buildablePreProjects.map(p => `build-${p.name}`))
            .addMetaTarget('build-pre-provision', ['build-pre-plan'])
            .addMetaTarget('build-post-provision', buildablePostProjects.map(p => `build-${p.name}`))
            .addMetaTarget('test', testableProjects.map(p => `test-${p.name}`))
            .addSubTarget('provision', 'infra', 'provision', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('provision-full', 'infra', 'provision-full', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-init', 'infra', 'init', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-plan', 'infra', 'plan', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-apply', 'infra', 'apply', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-refresh', 'infra', 'refresh', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-update', 'infra', 'update', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('list-layers', 'infra', 'list-layers', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-init-full', 'infra', 'init-full', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-init-full-upgrade', 'infra', 'init-full-upgrade', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-destroy', 'infra', 'destroy', {env: '$(env)', layer: '$(layer)'}, ['generate-terraform'])
            .addSubTarget('output', 'infra', 'output', {env: '$(env)', layer: '$(layer)'}, ['generate-terraform'])
            .addSubTarget('output-json', 'infra', 'output-json', {env: '$(env)', layer: '$(layer)'}, ['generate-terraform'])
            .addSubTarget('outputs', 'infra', 'outputs', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('infra-init-upgrade', 'infra', 'init-upgrade', {env: '$(env)'}, ['generate-terraform'])
            .addSubTarget('generate-terraform', 'infra', 'generate')
            .addMetaTarget('generate-env-local', generateEnvLocalableProjects.map(p => `generate-env-local-${p.name}`))
            .addMetaTarget('pre-install', ['pre-install-root', ...preInstallableProjects.map(p => `pre-install-${p.name}`)])
            .addMetaTarget('install', ['install-root', ...installableProjects.map(p => `install-${p.name}`)])
            .addTarget('start', [vars.startCmd || `npx concurrently -n ${startableProjects.map(p => p.name)} ${startableProjects.map(p => `"make start-${p.name}"`).join(' ')}`])
            .setDefaultTarget('install')
        ;
        preInstallableProjects.forEach(p => {
            t.addSubTarget(`pre-install-${p.name}`, p.name, 'pre-install');
        });
        installableProjects.forEach(p => {
            t.addSubTarget(`install-${p.name}`, p.name, 'install');
        });
        testableProjects.forEach(p => {
            t.addSubTarget(`test-${p.name}`, p.name, 'test');
        });
        generateEnvLocalableProjects.forEach(p => {
            t.addSubTarget(`generate-env-local-${p.name}`, p.name, 'generate-env-local', {env: '$(env)'});
        });
        buildableProjects.forEach(p => {
            t.addSubTarget(`build-${p.name}`, p.name, 'build', {env: '$(env)'}, [`generate-env-local-${p.name}`]);
        });
        deployableProjects.forEach(p => {
            !!p.deployable && t.addSubTarget(`deploy-${p.name}`, p.name, 'deploy', {env: '$(env)'}, [`generate-env-local-${p.name}`], {sourceEnvLocal: true});
        });
        refreshableProjects.forEach(p => {
            !!p.refreshable && t.addSubTarget(`refresh-${p.name}`, 'infra', 'provision', {env: '$(env)', layer: p.name}, ['generate-terraform', `build-${p.name}`]);
        });
        startableProjects.forEach(p => {
            !!p.startable && t.addSubTarget(`start-${p.name}`, p.name, 'start', {env: '$(env)'});
        });
        ('github' === scm) && t.addTarget('pr', ['hub pull-request -b $(b)']);
        return t;
    }
    protected getTechnologies(): any {
        const technos = {
            microgen: {name: "MicroGen", link: "https://github.com/ohoareau/microgen"},
            make: {name: "Make / Makefile", link: "https://www.gnu.org/software/make/manual/make.html"},
            aws: {name: "Amazon Web Services (AWS)", link: "https://aws.amazon.com/"},
            aws_cli: {name: "AWS CLI", link: "https://aws.amazon.com/fr/cli/"},
            nodejs: {name: "Node.js", link: "https://nodejs.org/en/"},
            js_es6: {name: "Javascript (ES6)", link: "http://es6-features.org/"},
            yarn: {name: "Yarn", link: "https://yarnpkg.com/"},
            nvm: {name: "NVM", link: "https://github.com/nvm-sh/nvm"},
            npm: {name: "NPM", link: "https://www.npmjs.com/"},
            markdown: {name: "Markdown", link: "https://guides.github.com/features/mastering-markdown/"},
            git: {name: "Git", link: "https://git-scm.com/"},
            json: {name: "JSON", link: "https://www.json.org/json-fr.html"},
        };
        switch (this.vars.scm) {
            case 'github':
                technos['github'] = {name: "GitHub", link: "https://github.com/"};
                technos['github_actions'] = {name: "GitHub Actions", link: "https://github.com/features/actions"};
                technos['github_packages'] = {name: "GitHub Packages", link: "https://github.com/features/packages"};
                break;
            case 'gitlab':
                technos['gitlab'] = {name: "Gitlab", link: "https://gitlab.com/"};
                break;
        }
        return technos;
    }
}